version: '3.4'

services:
  b2b-portal:
    image: baims/b2b-portal:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
      - 9229:9229
